- name: configuring shipping component
  hosts: shipping
  become: yes
  tasks: 
  - name: installing maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - maven
      - mysql

  - name: install PyMySQL and cryptography 
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL


  - name: add roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      comment: roboshop system user
      system: true
      home: /app

  - name: create a /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the shipping component code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      path: /tmp/shipping.zip

  - name: extract the downloaded code
    ansible.builtin.unarchive: 
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install the dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move .jar file
    ansible.builtin.command:  mv target/shipping-1.0.jar shipping.jar
    args: 
      chdir: /app

  - name: copy and setup systemd service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: service daemon_reload
    ansible.builtin.systemd_service: 
      daemon_reload: true

  - name: start and enable shipping service
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes

   # - name: connect to mysql using app user
  #   community.mysql.mysql_info:
  #     login_user: shipping
  #     login_password: RoboShop@1
  #     login_host: mysql.daws84s.site
  #     login_db: cities

  - name: import data
    tags:
    - import
    community.mysql.mysql_db:
      name: all
      login_user: root
      login_password: RoboShop@1
      login_host: mysql.daws84s.site
      state: import
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: restart shipping
    tags:
    - import
    ansible.builtin.service:
      state: restarted
      name: shipping
  